/**
 * @file Automatically generated by barrelsby.
 */

export * from "./ai-assistant.controller";
export * from "./auth.controller";
export * from "./aws.controller";
export * from "./health.controller";
export * from "./my-garage.controller";
export * from "./my-orders.controller";
export * from "./my-service.controller";
export * from "./notification.controller";
export * from "./service-catalog.controller";
export * from "./service-order.controller";
export * from "./service-provider.controller";
export * from "./user.controller";
export * from "./vehicle-catalog.controller";
